name: Deploy via FTP
on: workflow_dispatch
jobs:
  deploy_to_production:
    name: Deploy to Production
    uses: ./.github/workflows/deployment_workflow.yml
    with:
      environment: "Production"
  deploy_to_testing:
    name: Deploy to Testing
    uses: ./.github/workflows/deployment_workflow.yml
    with:
      environment: "Test"
