name: Deploy to Production via FTP
on: workflow_dispatch
jobs:
  deploy:
    name: Deploy to Production
    secrets: inherit
    uses: ./.github/workflows/deployment_workflow.yml
    with:
      environment: "Production"
